spring:
  datasource:
    url: "jdbc:mysql://localhost/post"
    username: "root"
    password: "Chldkdud00!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: dKyT4H44Tts8uFqJfiBc
            client-secret: YfHUdOZdEk
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 코드를 발급받을 우리 서버측 url
            authorization-grant-type: authorization_code # 코드 방식
            scope: # 이름과 이메일 값을 받음
              - name
              - email
          google:
            client-name: google
            client-id: 783185045242-5id49235kfouv8ctakcoft70pk6f3is7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  jwt:
    access:
      expiration: 6000000
    refresh:
      expiration: 86400000
    secretKey: asjdhakljshfdkljsahdfkjahsdfkjhsadkfhkasdfhkjsah2kj3h123123134413523487
